const mongoose=require("mongoose");

const userSchema=new mongoose.Schema({
    firstName:{
        type:String,
        required:true,
        trim:true,
    },
    lastName:{
        type:String,
        required:true,
        trim:true
    },
    password:{
        type:String,
        required:true
    },
    aadharNumber:{
        type:Number,
        required:true
    },
    contactNumber:{
        type:Number,
        required:true,
    },
    token:{
        type:String
    },
    gender:{
        type:String,
        enum:["Female"]
    },
    address:{
        type:String,
    },
    closestContacts:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"ClosestContact"
        }
    ],
    menstrualCycle:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"menstrualCycle"
    },
    complaint:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Complaint"
    }
})

module.exports=mongoose.model("User",userSchema);